import Footer from "@/components/common/Footer";
import "./globals.css";
import Header from "@/components/common/Header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="pb-[56px] md:pb-0">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
