import Footer from "@/components/common/Footer";
import "./globals.css";
import Header from "@/components/common/Header";
export const metadata = {
  metadataBase: "https://car-sell-alpha.vercel.app/",
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Create Next App",
    description: "Generated by create next app",
    images: ["/meta-image.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="pb-11 md:pb-0">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
